//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Que.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Que.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1313182641_button_black_play {
            get {
                object obj = ResourceManager.GetObject("1313182641_button_black_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1313182671_button_black_pause {
            get {
                object obj = ResourceManager.GetObject("1313182671_button_black_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1313182712_button_black_last {
            get {
                object obj = ResourceManager.GetObject("1313182712_button_black_last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1313272364_delete {
            get {
                object obj = ResourceManager.GetObject("1313272364_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Que REST service&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	&lt;h1&gt;Que REST service&lt;/h1&gt;
        ///    &lt;h2&gt;Now Playing&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        &lt;a href=&quot;/NowPlaying&quot;&gt;/NowPlaying&lt;/a&gt;
        ///    &lt;/p&gt;
        ///
        ///    &lt;h2&gt;Search&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        &lt;a href=&quot;/Search/monkey&quot;&gt;/Search/&amp;lt;query&amp;gt;&lt;/a&gt;
        ///    &lt;/p&gt;
        ///
        ///    &lt;h2&gt;Enqueue&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        &lt;a href=&quot;/Enqueue/link&quot;&gt;/Enqueue/&amp;lt;track link string&amp;gt;&lt;/a&gt;
        ///    &lt;/p&gt;
        ///
        ///    &lt;h2&gt;Image&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap unknown_album_cover {
            get {
                object obj = ResourceManager.GetObject("unknown_album_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
